### ISSUE TITLE
Invalid landing page categories

### ISSUE THREAD

**Issue by kvsun-editor** [KVSun/KV-Sun-WP#2]
The sections displayed on the home page are selected by category ID, which will be specific to a database. These need to be done by something more consistent, such as the actual textual value.

Ideally, this would be configurable in admin, but that could be done later.

**Comment by karanpal-insonix** [comment]
Chris, we can use name or slug for the category in place of id. Let me know which one you want to use.

**Comment by kvsun-editor** [comment]
I think slug should be good. How difficult would it be to make this something that we can add and customize rather than being hard-coded? If it's not a simple thing, can we use the slug for News, Sports News, Valley Life, and Opinion?

Maybe simplify this by using a `foreach($slugs_array)...` inside of a single file rather than have a separate one for each category.

**Comment by kvsun-editor** [comment]
Resolved in pull request #21
