### ISSUE TITLE
Import archives from TownNews

### ISSUE THREAD

**Issue by shgysk8zer0** [KVSun/KV-Sun-WP#29]
Once again, this will not be code that is committed.
Will need to parse the XML export given by TownNews and import the data into the WP database.

This does not need to be completed immediately, but should be ASAP.

**Comment by shgysk8zer0** [comment]
Not sure if the exports will include media.

**Comment by kvsun-editor** [comment]
For assistance, see [sample archive](https://cloud.kvsun.com/s/V1vcefsG9FaVwUI)
