### ISSUE TITLE
Update name and data

### ISSUE THREAD

**Issue by kvsun-editor** [KVSun/KV-Sun-WP#4]
This should no longer make references to the original theme / site except what is required by the licensing.

Most importantly, the theme should not use the same name or update link.
I am also requesting that all class names, etc. be updated to reflect the new theme name/info instead of BresponZive.

**Comment by karanpal-insonix** [comment]
Hi Chris. 

For this task, here is one solution proposed by someone on stackoverflow. 
http://stackoverflow.com/questions/24123059/how-to-disable-theme-updates-on-wordpress-to-avoid-losing-my-changes

Please let me know if we can proceed using above solution.

**Comment by kvsun-editor** [comment]
There are several solutions mentioned here. I would like to have this be its own theme entirely. We might eventually publish this. We just don't have a URL for it yet.

**Comment by shgysk8zer0** [comment]
I have updated `style.css` but do not know how or where to change other things. Good enough for now, but I'm still leaving this issue open for future work.

**Comment by shgysk8zer0** [comment]
Fixed in commit cc68674ba51fb303fe1daf72d06a0a4f18e1af6e
