### ISSUE TITLE
Break index.php into components

### ISSUE THREAD

**Issue by shgysk8zer0** [KVSun/KV-Sun-WP#7]
This should not all be contained in a single file.

**Comment by kvsun-editor** [comment]
This is what was discussed about a "monolithic" `index.php`.

**Comment by Sachinlath** [comment]
In progress. It should be done by tomorrow.

**Comment by Sachinlath** [comment]
Done,Code committed and pushed.

**Comment by kvsun-editor** [comment]
Please create a pull-request. On #6 as well.
