### ISSUE TITLE
Fix resource organisation

### ISSUE THREAD

**Issue by shgysk8zer0** [KVSun/KV-Sun-WP#8]
The stylesheet used (`style.css`) is located in the theme directory. There is also a duplicate and outdated stylesheet in the proper location. This is poor organization and can lead to confusion.

**Comment by shgysk8zer0** [comment]
Should probably also start breaking `style.css` into different stylesheets.

**Comment by karanpal-insonix** [comment]
Hi Chris. 
I have spoken to our designer about this, and he is of the view that using @import will result in poor performance as well as site ranking issues.

**Comment by shgysk8zer0** [comment]
That is what Myth is for. This will improve performance and 
compatibility.

Chris Zuber ‐ Full Stack Web Developer
shgysk8zer0@gmail.com

chriszuber.com
